spring.application.name=rasplus-data-api
server.servlet.context-path=/api/data
server.port=8084
spring.datasource.url=jdbc:mysql://localhost:3306/RASPLUS
spring.datasource.username=rasmoo
spring.datasource.password=senha123