spring.application.name=rasplus-teste-data-api
server.servlet.context-path=/data/api
server.port=8084
spring.datasource.url=jdbc:mysql://localhost:3306/RASPLUS
spring.datasource.username=rasmoo
spring.datasource.password=senha123